= cp4ba-install-helper
:toc: left
:toc-title: Table of Contents

This repo includes instructions and scripts to install IBM Cloud Pak for Business Automation in a certain way, suitable for demonstrations and development.

The certain way of installation means CP4BA production installation where Active Directory and MongoDB are installed on the same namespace.

Installation is based on documentation: https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/24.0.0. 

== Prepare for installation

* OpenShift cluster and cluster admin access to it.
** OpenShift 4.12, 4.14 and  4.15 are supported. See docs for latest information.
* Storageclasses that supports RWX and RWO.
** OpenShift Data Foundation (ODF) is a great choice.
** Both file and block storage is required.
* Get IBM entitlement key from https://myibm.ibm.com/products-services/containerlibrary.
* Clone or download this repository to your workstation or server.
** Bash-shell and Linux preferred.

== Create user

CP4BA installation asks for user during installation. If not already available, you may use script link:htpasswd/htpasswd-util.sh[htpasswd-util.sh] to create htpasswd provider and add/remove users.

* Create htpasswd provider and _cladmin_-user.

```
./htpasswd-util.sh create
```

== Set up environment variables

* Export these environment variables:
```
export CP4BA_VERSION=24.0.0-IF002
export CP4BA_NAMESPACE=cp4ba
export LDAP_USER_PASSWORD="passw0rd"
```

* _CP4BA_VERSION_ is the version/branch of CP4BA. See https://github.com/icp4a/cert-kubernetes for the latest version/branch.
* _CP4BA_NAMESPACE_ is the namespace where CP4BA will be installed.
* _LDAP_USER_PASSWORD_ is the password for all users in Active Directory.
* If using CP4BA v.23.x, see branch _23.x_.

== Install prerequirements

CP4BA requires LDAP and databases.

* This script installs Active Directory, MongoDB and Gitea.

```
./install-cp4ba-prereqs.sh
```

* MongoDB is required by ADP and ADS.
* Gitea is used by ADS and ADP.
* Note: PostgreSQL is used by all capabilities and it is installed by CP4BA operator.

=== Active Directory demo

Active Directory used in here is Samba Active Directory (same functionality as Microsoft Active Directory) and implemented by https://github.com/samisalkosuo/activedirectory-demo.

Users and groups are the same as in the demo, with following additional users:

* Group: _staff_.
** Users in _staff_: _user1,user2,user3,user4,user5,user6,user7,user8,user9,user10_.
* Group _admin_ has also user _cp4admin_.

=== Gitea

Git is used by both Automation Decision Services and Automation Document Processing. If you create either type of automations, you may use Gitea that is installed as a prereq. 

Alternatively, GitHub or other Git provider can be used.

* Gitea information (URL, repositories, credentials) are in _prereq-cp4ba-gitea-info_-ConfigMap in the _CP4BA_NAMESPACE_-namespace.
* Note: Gitea uses certificate provided by OpenShift router. If that certificate is self-signed, additional configuration is needed by ADP: https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/23.0.2?topic=processing-preparing-git-connection.

== Clone CP4BA cert-kubernetes

Scripts that are used to install CP4BA are in GitHub repository. Use script to clone it.

```
./clone-cp4ba-repository.sh
```

== Cluster setup

Cluster setup installs, if not already installed, necessary operator catalogs,IBM Certificate Manager and IBM Licensing cluster-wide services as well as CP4BA operators to chosen namespace.

Note: this can be used multiple times in multiple namespaces so you can install CP4BA multiple times in the same cluster. Remember to modify environment variables when installing to a new namespace.

* Go to directory:
```
$CP4BA_VERSION/cert-kubernetes/scripts
```

* Execute:
```
./cp4a-clusteradmin-setup.sh
```

* Follow the instructions in the script.
* For example, set following parameters:
** Airgap or online: _online_.
** OpenShift platform: _private_.
** Deployment: _production_.
** FIPS check: _no_.
** Private catalog: _yes/no_.
*** Select _yes_, if you want catalog sources to be namespace scoped.
** Separate operators and operands: _yes/no_.
** Select _no_, if you want operators and operands to be in the same namespace.
** Namespace: your chosen namespace.
** Select user
** Enter registry key
* Wait until operators are installed.

== CP4BA prerequisites - create property files

CP4BA includes helper script to set up prereqs like secrets and database tables.

* Go to directory:
```
$CP4BA_VERSION/cert-kubernetes/scripts
```

* Execute:
```
./cp4a-prerequisites.sh -m property -n $CP4BA_NAMESPACE
```
* This script asks what to install and creates property files to be updated.
* Follow the instructions in the script.
* Select desired capabilities.
** Capalities and capability patterns is described https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/24.0.0?topic=deployment-capability-patterns-production-deployments[here].
* Select Microsoft Active Directory as LDAP.
* RWX storage, for example:
```
ocs-storagecluster-cephfs
```
* RWO storage, for example: 
```
ocs-storagecluster-ceph-rbd
```
* Select small deployment profile.
* Select _PostgreSQL EDB_ database.
* Do not restrict network egress.
** Restrict only in production environments, if you know what you are doing.
* Select NO when asked about external databases for IM metastore, Zen metastore and BTS metastore.
* Use default for external certificate.
* If asked, select 1 additional object store.
* If asked, select Yes as limited CPE storage support.
** If selecting No, it consumes licenses.
* The script generates property files that need to be modified:
** `cp4ba_LDAP.property`
** `cp4ba_user_profile.property`
* The next section describes what to do with the property files.
** Property file content varies, depending on the chosen capabilities.

== CP4BA prerequisites - edit property files

Prereq property files must be edited to include, for example, user names and password and database connection information.

Follow instructions in link:property-files[property-files]-directory to edit property files either manually or using scripts.

* This script modifies all property files:
```
./property-files/modify-all-property-files.sh
```

== CP4BA prerequisites - generate secrets

After the property files have been modified, _cp4a-prerequisites.sh_-script is used to generate secrets.

* Go to directory:
```
$CP4BA_VERSION/cert-kubernetes/scripts
```
* Execute:
```
./cp4a-prerequisites.sh -m generate -n $CP4BA_NAMESPACE
```

* Secret-files are created.
* Change to your chosen namespace.
** For example: `oc project cp4ba`

=== Create secrets

* Change to directory 
```
cp4ba-prerequisites/project/$CP4BA_NAMESPACE
```
* Execute:
```
./create_secret.sh
```
* This creates required secrets.

== CP4BA prerequisites - validate

This step is optional. Validation uses _cp4a-prerequisites.sh_-script to verify that secrets are created and LDAP is can be connected.
Since LDAP is inside the cluster, verification needs to be done from CP4BA operator container.

This is documented https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/24.0.0?topic=pycc-recommended-preparing-databases-secrets-your-chosen-capabilities-by-running-script and step 9. 

Alternatively:

* Execute: 
```
./validate/validate-prereqs.sh
```
* Script packages _cert-kubernetes_-directory and copies files to operator pod.
* Follow instructions in the script.

== CP4BA installation

Now that prereqs are complete, we can install CP4BA.

* Go to directory:
```
$CP4BA_VERSION/cert-kubernetes/scripts
```

* Execute:
```
./cp4a-deployment.sh -n $CP4BA_NAMESPACE
```

* Accept license.
* Select no when asked about Content CR.
* Select Production deployment.
* Capabilities that were chosen previously is listed.
* Select OpenShift private cloud.
* Select yes to use default admin.
* Press enter when asked about JDBC drivers.
* Enter 'Yes' to proceed with deployment.
* CP4BA custom CR YAML-file is created.
** File is: `generated-cr/ibm_cp4a_cr_final.yaml`
* Optionally, verify the generated YAML.
** Check also link:Troubleshooting.adoc[Troubleshooting.adoc].
* Apply YAML:
```
oc apply -f generated-cr/project/$CP4BA_NAMESPACE/ibm_cp4a_cr_final.yaml
```

== CP4BA installation - follow

Follow the installation using OpenShift console and the following scripts.

```
./cp4a-post-install.sh --Status
```
* Prints the status of the installation.


== CP4BA installation - done

When installation is complete, you can check username, password and URLs using the following command.

```
./cp4a-post-install.sh --Console
```
