= cp4ba-install-helper
:toc: left
:toc-title: Table of Contents

This repo includes instructions and scripts to install IBM Cloud Pak for Business Automation in a certain way, suitable for demonstrations and development.

The certain way of installation means CP4BA production installation where Active Directory, PostgreSQL and MongoDB are installed on the same namespace.

Installation is based on documentation: https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/23.0.2. 

== Prepare for installation

* OpenShift cluster and cluster admin access to it.
** OpenShift 4.14 is supported by https://www.ibm.com/support/pages/node/7128178[CP4BA 23.0.2 IF003].
* Get IBM entitlement key from https://myibm.ibm.com/products-services/containerlibrary.
* Clone or download this repository to your workstation or server.
** These scripts have been tested with Rocky Linux 9.3 running inside https://github.com/samisalkosuo/devcon[container].

== Create user

CP4BA installation asks for user during installation. If not already available, you may use script link:htpasswd/htpasswd-util.sh[htpasswd-util.sh] to create htpasswd provider and add/remove users.

* Create htpasswd provider and _cladmin_-user.
```
./htpasswd-util.sh create
```

== Set up environment variables

* Export these environment variables:
```
export CP4BA_NAMESPACE=cp4ba
export CP4BA_CASE_VERSION=5.1.4
export LDAP_USER_PASSWORD="passw0rd"
```

* _CP4BA_NAMESPACE_ is the namespace where CP4BA will be installed.
* _CP4BA_CASE_VERSION_ is the case version. Check latest version from https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-cp-automation.
* _LDAP_USER_PASSWORD_ is the password for all users in Active Directory.

== Install prerequirements

CP4BA requires LDAP and databases.

* This script installs Active Directory, PostgreSQL and MongoDB.

```
./install-cp4ba-prereqs.sh
```

* PostgreSQL is used by all capabilities.
* MongoDB is required by ADS and optional by ADP.

=== Active Directory demo

Active Directory used in here is Samba Active Directory (same functionality as Microsoft Active Directory) and implemented by https://github.com/samisalkosuo/activedirectory-demo.

Users and groups are the same as in the demo, with following additional users:

* Group: _staff_.
** Users in _staff_: _user1,user2,user3,user4,user5,user6,user7,user8,user9,user10_.
* Group admin has also user _cp4admin_.

== Download case file

CP4BA case file is published to GitHub. Check latest version from https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-cp-automation.

Download case file using script:

```
./download-cp4ba-case-file.sh
```

* The case version was specified earlier in _CP4BA_CASE_VERSION_ environment variable.
* Script downloads and extracts the file to `<version>/cert-kubernetes`
* `<version>/cert-kubernetes/scripts` includes scripts that will be used.

== Cluster setup

Cluster setup installs, if not already installed, necessary operator catalogs,IBM Certificate Manager and IBM Licensing cluster-wide services as well as CP4BA operators to chosen namespace.

Note: this can be used multiple times in multiple namespaces so you can install CP4BA multiple times in the same cluster. Remember to modify environment variables when installing to a new namespace.

* Go to directory:
```
$CP4BA_CASE_VERSION/cert-kubernetes/scripts
```

* Execute:
```
./cp4a-clusteradmin-setup.sh
```
* Follow the instructions in the script.
* For example, set following parameters:
** OpenShift platform: private
** Deployment: production
** FIPS check: no
** Private catalog: yes/no
*** Select yes if you want catalog sources to be namespace scoped.
** Namespace: your chosen namespace 
** Select user
** Enter registry key
* Wait until operators are installed

== CP4BA prerequisites - create property files

CP4BA includes helper script to set up prereqs like secrets and database tables.

* Go to directory:
```
$CP4BA_CASE_VERSION/cert-kubernetes/scripts
```

* Execute:
```
./cp4a-prerequisites.sh -m property
```
* This script asks what to install and creates property files to be updated.
* Follow the instructions in the script.
* Select desired capabilities.
** Capalities and capability patterns is described https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/23.0.2?topic=deployment-capability-patterns-production-deployments[here].
* Select Microsoft Active Directory as LDAP.
* RWX storage: 
```
ocs-storagecluster-cephfs
```
* RWO storage: 
```
ocs-storagecluster-ceph-rbd
```
* Select small deployment profile.
* Select PostgreSQL database.
* Enter database server alias name:
```
dbserver1
```
* Enter chosen namespace.
* Do not restrict network egress.
** Restrict only in production environments, if you know what you are doing.
* Select 1 additional object store.
* Select Yes as limited CPE storage support.
** If selecting No, it consumes licenses.
* The script generates property files that need to be modified:
** `cp4ba_db_name_user.property`
** `cp4ba_db_server.property`
** `cp4ba_LDAP.property`
** `cp4ba_user_profile.property`
* The next section describes what to do with the property files.
** Property file content varies, depending on the chosen capabilities.

== CP4BA prerequisites - edit property files

Prereq property files must be edited to include, for example, user names and password and database connection information.

Follow instructions in link:property-files[property-files]-directory to edit property files either manually or using scripts.

== CP4BA prerequisites - generate SQL and secrets

After the property files have been modified, _cp4a-prerequisites.sh_-script is used to generate SQL statements and secrets.

* Go to directory:
```
$CP4BA_CASE_VERSION/cert-kubernetes/scripts
```
* Execute:
```
./cp4a-prerequisites.sh -m generate
```

* SQL statement files and secret-files are created.
* Change to your chosen namespace.
** For example: `oc project cp4ba`

=== Create secrets

* Change to directory `cp4ba-prerequisites`
* Execute:
```
./create_secret.sh
```
* This creates required secrets.

=== Create databases

* Execute: 
```
./database/execute-cp4ba-postgresql-dbscripts.sh
```
* This copies SQL scripts inside PostgreSQL container and executes them to create required databases.

== CP4BA prerequisites - validate

This step is optional. Validation uses _cp4a-prerequisites.sh_-script to verify that secrets and databases are created.
Since database is inside the cluster, verification needs to be done from CP4BA operator container.

This is documented https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/23.0.2?topic=pycc-recommended-preparing-databases-secrets-your-chosen-capabilities-by-running-script and step 9. 

Alternatively:

* Execute: 
```
./validate/validate-prereqs.sh
```
* Script packages _cert-kubernetes_-directory and copies files to operator pod.
* Follow instructions in the script.

== CP4BA installation

Now that prereqs are complete, we can install CP4BA.

* Go to directory:
```
$CP4BA_CASE_VERSION/cert-kubernetes/scripts
```

* Execute:
```
./cp4a-deployment.sh
```

* Accept license.
* Select no when asked about Content CR.
* Select Production deployment.
* Capabilities that were chosen previously is listed.
* Select OpenShift private cloud.
* Select yes to use default admin.
* Press enter when asked about JDBC drivers.
* Enter 'Yes' to proceed with deployment.
* CP4BA custom CR YAML-file is created.
** File is: `generated-cr/ibm_cp4a_cr_final.yaml`
* Apply YAML:
** Change to chosen namespace.
```
oc apply -f generated-cr/ibm_cp4a_cr_final.yaml
```


== CP4BA installation - follow

Follow the installation using OpenShift console and the following scripts.

```
./cp4a-post-install.sh --Status
```
* Prints the status of the installation.


== CP4BA installation - done

When installation is complete, you can check username, password and URLs using the following command.

```
./cp4a-post-install.sh --Console
```
