#from https://phoenixnap.com/kb/kubernetes-mongodb
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {PREFIX}mongodb-pvc
  namespace: {NAMESPACE}
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: {PREFIX}mongodb-secret
  namespace: {NAMESPACE}
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: "passw0rd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {PREFIX}mongodb-configmap
  namespace: {NAMESPACE}
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {PREFIX}mongodb
  namespace: {NAMESPACE}
spec:
  serviceName: {PREFIX}mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: {PREFIX}mongodb
  template:
    metadata:
      labels:
        app: {PREFIX}mongodb
    spec:
      containers:
      - name: {PREFIX}mongodb
        image: mongo:5
        resources:
          limits:
            cpu: 2000m
            memory: 4096M
          requests:
            cpu: 500m
            memory: 1024M
        env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/k8-test/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/k8-test/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: k8-test
          mountPath: /etc/k8-test
          readOnly: true
        - name: {PREFIX}mongodb-configmap
          mountPath: /config
          readOnly: true
        - name: {PREFIX}mongodb-data
          mountPath: /data/db
      volumes:
      - name: k8-test
        secret:
          secretName: {PREFIX}mongodb-secret
          items:
          - key: MONGO_ROOT_USERNAME
            path: MONGO_ROOT_USERNAME
            mode: 0444
          - key: MONGO_ROOT_PASSWORD
            path: MONGO_ROOT_PASSWORD
            mode: 0444
      - name: {PREFIX}mongodb-configmap
        configMap:
          name: {PREFIX}mongodb-configmap
          items:
          - key: mongo.conf
            path: mongo.conf
      - name: {PREFIX}mongodb-data
        persistentVolumeClaim:
          claimName: {PREFIX}mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {PREFIX}mongodb-svc
  namespace: {NAMESPACE}
  labels:
    app: {PREFIX}mongodb
spec:
  selector:
    app: {PREFIX}mongodb
  ports:
    - port: 27017
